version: 2.1
jobs:

  build:
    docker:
      - image: circleci/node:12.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm run compile
      - run: npm run unittest

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: nightly, master